name: mcc
channels:
  - defaults
  - conda-forge
  - r
  - bioconda
dependencies:
  - python=3.8
  - ipykernel
  - nb_conda_kernels
  - rpy2
  - scikit-image
  - statsmodels
  - r-base=3.6.3
  - r-circlize
  - r-data.table
  - r-future
  - r-future.apply
  - r-ggplot2
  - r-igraph
  - r-mltools
  - r-tidyverse
  - bioconductor-complexheatmap
  - pip:
      - graspologic @ git+git://github.com/microsoft/graspologic@9c65548b7ead45d620e71d2b08763f83555262c0
      - nb-black
