#!/bin/bash
set -ex

function execute_nb {
    jupyter nbconvert \
        --ExecutePreprocessor.kernel_name=python3 \
        --ExecutePreprocessor.allow_errors=False \
        --ExecutePreprocessor.timeout=-1 \
        --FilesWriter.build_directory==../results \
        --to "html" \
        --execute $1
}

execute_nb 4-strong-signal-components/identifying_signal_components.ipynb