#!/bin/bash
set -ex

function execute_nb {
    jupyter nbconvert \
        --ExecutePreprocessor.kernel_name=python3 \
        --ExecutePreprocessor.allow_errors=False \
        --ExecutePreprocessor.timeout=-1 \
        --FilesWriter.build_directory==../results \
        --to "html" \
        --execute $1
}

execute_nb 1_statistical_framework_graphs.ipynb
execute_nb 2_plot_adjacency_matrices.ipynb
execute_nb 4a_identifying_signal_components.ipynb
execute_nb 4b_format_signal_components_tables.ipynb
execute_nb 5_whole_brain_emedding.ipynb